// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPHHy_9mIpIpiDUE2DzLVZgEVqEwWCDsg',
    appId: '1:794706907727:web:8f03c37dadd5261efdd03a',
    messagingSenderId: '794706907727',
    projectId: 'fasum-17650',
    authDomain: 'fasum-17650.firebaseapp.com',
    storageBucket: 'fasum-17650.appspot.com',
    measurementId: 'G-RJNGVYP95W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq_ZuQfmaUvgGxmdcKz6qgJBsJKhMfGT0',
    appId: '1:794706907727:android:fedc610acfd2322ffdd03a',
    messagingSenderId: '794706907727',
    projectId: 'fasum-17650',
    storageBucket: 'fasum-17650.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqhX6nT85B2PUk-88NqPXkr8m6r_RpXr4',
    appId: '1:794706907727:ios:91ab3122ed67baa0fdd03a',
    messagingSenderId: '794706907727',
    projectId: 'fasum-17650',
    storageBucket: 'fasum-17650.appspot.com',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqhX6nT85B2PUk-88NqPXkr8m6r_RpXr4',
    appId: '1:794706907727:ios:79fc2d4d7c6306c6fdd03a',
    messagingSenderId: '794706907727',
    projectId: 'fasum-17650',
    storageBucket: 'fasum-17650.appspot.com',
    iosBundleId: 'com.example.fasum.RunnerTests',
  );
}
